### ISSUE TITLE
Lists of elements with information if there's more

### ISSUE THREAD

**Issue by mszymczakowski** [darrenparkinson/SparkDotNet#1]
Is there any way to know if there are more items in list?
For example I'm getting last 100 messages in room, but there are more of them in room.
Is there a way in your library to get this info? It's in "Link" header.

**Comment by darrenparkinson** [comment]
Good spot, thanks.  No it does not currently provide that.  I will use the [Cisco Docs](https://developer.ciscospark.com/pagination.html) to see how best to implement it.  Any preferences?

**Comment by mszymczakowski** [comment]
You can create overloaded methods (only those which return list of elements) with out bool parameter  saying if there's more, so if developer wants to know that there's something more he needs to use this method

just boolean, because you have the list, so you can query again with id of last element

this way project would be backward compatible

other problem I've found is that Room object doesn't have creatorId property, it's not marked in API, but in response you can find this property

**Comment by darrenparkinson** [comment]
Thanks for the input.

So do you mean an overload to GetMessagesAsync which has an additional boolean parameter like `more` which I can use to indicate more messages?

So something like the following:

```
public async Task<List<Message>> GetMessagesAsync(out more, string roomId, string mentionedPeople = null, string before = null, string beforeMessage = null, int max = 0)
```
And then I can just set that to `true` if there is a `link` header.

I assume you're saying that you could then use the `beforeMessage` parameter to specify the additional messages?

Would that be sufficient?  What about the `first` and `prev` links?

(Edit: I remembered `out` cannot be used on optional parameters)

**Comment by mszymczakowski** [comment]
I didn't thought about `first` and `prev`.. so my solution is useless now :(

What does `prev` and `first` have? Links to get previous and first page?

If true then you can instead of `List<Room>` return object like this:

```
public class RoomList
{
      public List<Room> Items { get; set; }
      public string Next { get; set; }
      public string Prev { get; set; }
      public string First { get; set; }
}
```

where `Next`, `Prev`, and `First` would be IDs of elements set in `beforeMessage` parameter
if there's no `next` link then `Next` property would be null

**Comment by darrenparkinson** [comment]
Thanks.  Yes, that's what I was initially thinking too.  So you wouldn't expect them to be the actual links to use, but rather just the id to be used in `beforeMessage`.  

Unfortunately, just looking at that, I'm not sure that would work either because it doesn't look like Cisco has been consistent with these.  I noticed in [the docs](https://developer.ciscospark.com/pagination.html) it suggests that `people` would have a before and after and the api docs don't provide anything similar to `beforeMessage` for people or rooms etc either... So it might just have to be the link if there is one...?

This is their people example:
```
Link: <https://api.ciscospark.com/v1/people?displayName=Harold&max=10&before&after=Y2lzY29zcGFyazovL3VzL1BFT1BMRS83MTZlOWQxYy1jYTQ0LTRmZWQtOGZjYS05ZGY0YjRmNDE3ZjU> rel="next"
```

**Comment by mszymczakowski** [comment]
Sure, you're right.
Link would be fine :)

**Comment by darrenparkinson** [comment]
Thanks. OK, I'll look into that, as that would definitely be a required feature.

**Comment by darrenparkinson** [comment]
Just looking at this and I forgot you can't use `out` with async methods, so that wouldn't work.  That basically means I can't overload the existing method as initially thought.  

So, to preserve backwards compatibility I was thinking I could overload it with an additional boolean parameter to say you'd like links that would also return the RoomList object instead:

```
public async Task<RoomList> GetMessagesAsync(string roomId, string mentionedPeople = null, string before = null, string beforeMessage = null, int max = 0, bool links = false)
```

But that causes ambiguity with the library so might break any existing code that uses `var` rather than specifies the object type.

The other option is to create a new method name entirely like `GetMessagesAsyncWithLinks`.

Any thoughts?

**Comment by darrenparkinson** [comment]
Spent a few minutes on this the other day.  One of the other issues we have is that if I give you back the links, the library doesn't actually have a way of making use of them, so I'll need to add in a method for that too...

At this point, I've created a `Links` class which can hold the Next, Prev and First items in an object:

```
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace SparkDotNet {
    public class Links
    {
        public string Next { get; set; }
        public string Prev { get; set; }
        public string First { get; set; }
        
       public override string ToString() {
            return JsonConvert.SerializeObject(this);
        }
    }
}
```

And I duplicated the private `GetItemsAsync` as `GetItemsWithLinksAsync<T>` which returns a `Task<Tuple<List<T>, Links>>` that can then be used by any of the different types to return the original list and the new `Links` object.  We could then use either of those with the Links too since they just accept a path. 

Finally, we'd need to add something to each of the relevant API Partials to enable the pagination.  This is where it seems to get a little messy, since we'll need a new method for GetMessagesAsync (to allow for backwards compatibility) along with a new method for getting Messages pages, and then duplicate that for each of the partials.

I'm just trying to think if there is a tidier way by introducing a generic pagination class or something...

**Comment by mszymczakowski** [comment]
I've thought about this too, and discovered the same issue. 

Can't we add just one generic method, for example `List<T> GetModelsFromLink<T>(string link)` that send query to URL, and then tries to return elements of specified generic type?

**Comment by darrenparkinson** [comment]
I guess we can go ahead and close this one now...
