### ISSUE TITLE
400 bad request exception 

### ISSUE THREAD

**Issue by PrakNarith** [darrenparkinson/SparkDotNet#11]
Hi, after I create message posting, it's respond with 400 bad request code when using string[] to upload file. It's ok if just posting with text.
 ```
Message message = new Message();
           message.roomId = "Access Token";
           message.files = Directory.GetFiles("C:\\Users\\Pictures\\2.jpg");
           message = await spark.CreateMessageAsync(message.roomId, message.files);
```

**Comment by darrenparkinson** [comment]
Hi @PrakNarith 

Looking at the [developer docs](https://developer.ciscospark.com/endpoint-messages-post.html) for Cisco, it says that `files` is 

> The public URL to a binary file to be posted into the room  

The files attribute doesn't work for locally held files.  I think to upload locally held files, they need to be added as a file in a multipart message rather than being specified in the "files" attribute in the JSON.  

I'll take a look to see how best to handle that.  If you have any thoughts, let me know.

Thanks for opening the issue.

D.

**Comment by coenvdam** [comment]
Hey @PrakNarith and @darrenparkinson 
I've also been trying to send local files with SparkDotNet. On developer.ciscospark.com there's two lines of documentation on it [here](https://developer.ciscospark.com/attachments.html): 

> To send attachments, simply post a message by including your access token in the _Authorization_ header and attach your local file with _files_ property. Optionally, you can also include your plain text message as part of the attachment in _text_ property
>>**curl -F "files=@/home/desktop/example.png;type=image/png" --request POST -H "Authorization: Bearer ACCESS_TOKEN" -F "roomId=Y2lzY2....." https://api.ciscospark.com/v1/messages -F "text=example attached"**

That doesn't really help though because you can't make cURL calls in C#. I personally don't really know how to do it either, so I'm stuck too. If you have any updates, let me know.

**Comment by darrenparkinson** [comment]
That helps a little since the `-F` option for `curl` specifies a `FORM`.  From the MAN page:

> This causes curl to POST data using the Content-Type multipart/form-data according to RFC 2388. This enables uploading of binary files etc.

There is also [this blog post](https://developer.ciscospark.com/blog/blog-details-8129.html) from Cisco that helps too,  The code is in python, but I should be able to translate that across.

Do you have a preference to how it is implemented?  I could either create a new method to call or it might be possible to add it to the existing `CreateMessageAsync` method?

**Comment by coenvdam** [comment]
I personally don't mind either way.

I asked the Cisco Spark Developer chat and they said that the file should be multi-part mime encoded. That happens if you use cURL, but not if you just put the string in the HTTP request.

**Comment by darrenparkinson** [comment]
OK, thanks.  Yes exactly.  Just taking a look now.  I normally catch things in the Spark Dev chat, but it can get quite busy in there, sorry about that.

**Comment by darrenparkinson** [comment]
So, @coenvdam / @PrakNarith I've updated the code to enable the acceptance of local file names in the CreateMessageAsync() method.  Give it a try and let me know what you think.  I'm about to update the nuget package now if you wanted to wait for that.

**Comment by coenvdam** [comment]
It works perfectly! Thanks for the quick fix.

**Comment by PrakNarith** [comment]
Sorry for late reply @coenvdam , I had been solve it since  @darrenparkinson's suggestion to use multipart form. I will test this later
