### ISSUE TITLE
library doesn't seem functional at this point

### ISSUE THREAD

**Issue by jlindborg** [darrenparkinson/SparkDotNet#13]
testing out this morning on a clean 4.6.2 C# app, I kept it real simple: 

        private void button1_Click(object sender, EventArgs e)
        {
            RunAsync().Wait();
        }

        async Task RunAsync()
        {
            var spark = new Spark("xxx");

            try
            {
                var oMe = await spark.GetMeAsync();
                Console.WriteLine(oMe.displayName);
            }
            catch (SparkException ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

no error is thrown, it just never returns from any call (I tried others besides GetMeAsync) - just freezes.  I used the same bearer token via Postman for various calls and it worked fine.

Since there's no error logging or events that can be hooked if there's an issue it's hard to tell what's going on here.  I did try forcing TSL 1.2 and the like (4.6 should do this by default anyway) but it didn't make any difference.

**Comment by darrenparkinson** [comment]
Apologies for the delay.  I should have some time this week to look into it.

**Comment by darrenparkinson** [comment]
I used your code with .Net Framework 4.6.2  as a console app and had no issues.  I get the same as you with a Windows Forms App and your code.  This is because you are experiencing a dead lock issue by blocking the UI.  This will be why you are getting no response.  To get around this issue it's just a case of understanding  asynchronous programming.  

Add the word `async` to your button1_click method and move your code into that method:

```
        private async void button1_Click(object sender, EventArgs e)
        {
            //RunAsync().Wait();
            var spark = new Spark("");

            try
            {
                var oMe = await spark.GetMeAsync();
                Console.WriteLine(oMe.displayName);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
```

This will resolve your issue.  Just for reference you might try using slightly less inflammatory issue descriptions.
